// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvTnT7KSrie2yfxS2OQfcmvp2A-D-s-D4',
    appId: '1:102742026996:web:5738c31f8e81c0ac734ca1',
    messagingSenderId: '102742026996',
    projectId: 'hackfusion-b5df5',
    authDomain: 'hackfusion-b5df5.firebaseapp.com',
    storageBucket: 'hackfusion-b5df5.firebasestorage.app',
    measurementId: 'G-FDYLM0CF0C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZxLWr1Usv3tAWdAgYA8l8fipyBoS00h8',
    appId: '1:102742026996:android:c11e273530ab3f1c734ca1',
    messagingSenderId: '102742026996',
    projectId: 'hackfusion-b5df5',
    storageBucket: 'hackfusion-b5df5.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAvTnT7KSrie2yfxS2OQfcmvp2A-D-s-D4',
    appId: '1:102742026996:web:7e420f217833d9b6734ca1',
    messagingSenderId: '102742026996',
    projectId: 'hackfusion-b5df5',
    authDomain: 'hackfusion-b5df5.firebaseapp.com',
    storageBucket: 'hackfusion-b5df5.firebasestorage.app',
    measurementId: 'G-SM7DJL4E2K',
  );
}
